### ISSUE TITLE
Missing data from Fackel-Persons

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#200]
Apparently we have not imported all persons. I.e. looking for "Feigl" in the Fackel Personenliste list 5 persons:
1 | Feigl, Johann (Hans) | INFO › | 101
2 | Melbourn, Josef | INFO › | 6
3 | Feigl, Eduard von | INFO › | 1
4 | Feigl, Wilhelm | INFO › | 1
5 | Feigl-Melbourn, Josef | INFO ›

none of them is in the PMB. We need to investigate why this is possible. Persons without GND still missing?

**Comment by martinantonmueller** [comment]
Investigating further: All "Feigl"s have no GND. 
But:
//person[not(idno[2])]
has 8699 results
and there are but 6509 fackel-person-uris stored in pmb
so i believe what happened is:
of all the 11.214 persons on fackel person
a subset of 6509 was imported with people where an GND could be detected (i.e. a new reconsiliation)
and the rest was then omitted.

**Comment by csae8092** [comment]
fix https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/list/?name=%2C+geb.&collection=25

**Comment by csae8092** [comment]
all missing persons imported; 
* personplace relations crated if there is a place with the same name -> I didn't create new places on purpose
* professions, if there is a profession in the existing vocabulary starting with the same string as the profession/occupation from the TEI/XML - use this, if there is not match, don't create new ones
* names, try to split on first `, `; if this is not possible, store the whole string from `persName` as `name`; except for names with `, geb.` -> the part after the `, geb.` was stored as label type `Person_Geburtsname_Nachname` (fixed with https://github.com/arthur-schnitzler/pmb-service/commit/95a6c05aef118f25f5c37c41f304b5878ead9b0e)

**Comment by martinantonmueller** [comment]
Peter on 🔥! Thank you!

**Comment by csae8092** [comment]
> Peter on 🔥! Thank you!

Ronja :sleeping:

**Comment by martinantonmueller** [comment]
Schlaf gut, Ronja!
