### ISSUE TITLE
limit relation in detail views to 250 per relation class

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/pmb-service#221]
as soon as all relation list views are established like in https://pmb.acdh.oeaw.ac.at/apis/relations/person-place/ I'd like to limit the number of relations displayed in the entity-detail view to ~ 250 per relation class BUT providing a link to the relation list views filtered by the current subject with some text like "Klicke hier um alle Verbindungen zu dieser Entität angezeigt zu bekommen"

@martinantonmueller any good objections

**Comment by martinantonmueller** [comment]
It looks really good! 

Two observations though: 
* this is the first time I would have access to the literal date field. before that it was always automatically filled via the other date field. I don't know if deviating from this is a good idea
* for now I can't really see the use of "copy relation". maybe this is because it allows for easier creation of similar entries, i.e. if I want to create relatioms for every time Schnitzler went on the ferris wheel and just the dates changed? Or his son went along and the date stays the same but the son of course is a different person?

**Comment by martinantonmueller** [comment]
I tried to use the copy feature but it immediately created a duplicate (which should be forbidden anyhow)
 the amount of fields is too much. it would be more meaningful to have the relevant fields at the top, i.e. target elements and dates

**Comment by csae8092** [comment]
> this is the first time I would have access to the literal date field. before that it was always automatically filled via the other date field. I don't know if deviating from this is a good idea

I changed the order of the fields

![image](https://github.com/user-attachments/assets/3da6b3b1-21c3-4156-bfb9-5b0d845ebeb5)

> "copy relation". maybe this is because it allows for easier creation of similar entries,

yes, that was the intended purpose

> created a duplicate 

see https://github.com/arthur-schnitzler/pmb-service/issues/225


and as of now, after editing/creating a new relation through an entities detail view, only the last (editied) view rows are returned; therefore heavy work on relations should be done in the dedicated relation views
