### ISSUE TITLE
(re)implement apis api

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/pmb-service#43]
especially those parts needed for apis-hub, because @martinantonmueller became a big fan of fancy networks

**Comment by martinantonmueller** [comment]
Yes, always when I need to write a proposal!

Am 02.01.2024 um 12:14 schrieb Peter Andorfer ***@***.***>:

﻿
External Email: please use links and attachments from trusted sources only

especially those parts needed for apis-hub, because @martinantonmueller<https://github.com/martinantonmueller> became a big fan of fancy networks

**Comment by martinantonmueller** [comment]
This is still not working – apis-hub appears unable to access PMB

**Comment by csae8092** [comment]
thats not entirly true, afaik person person are not loaded but e.g. person place relations as well
could you please provide a list here which relations dont work

**Comment by martinantonmueller** [comment]
will do. everything brings an error while loading. "typeError"

ALL relations with itself, i.e. event – event, person – person do not work

if you make combinations it does work

**Comment by martinantonmueller** [comment]
Of course this pops up again. If one tries to specify an entity (i.e. "Schnitzler") the dropdown field does not suggest any entities. And the TypeError in the lower left corner is still popping up consistently, e.g. when one runs empty "event" "event"-relations

**Comment by csae8092** [comment]
yeah
